### ISSUE TITLE
message handler error

### ISSUE THREAD

**Issue by arcontechnologies** [mrbot-ai/rasa-webchat#5]
Hello,

When running my bot, I'm getting this error message :

```
(base) C:\Users\Albel\Documents\demobotdc>python bot.py
2018-10-02 18:31:29.374440: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
127.0.0.1 - - [2018-10-02 18:31:50] "GET /socket.io/?EIO=3&transport=polling&t=MOrdnFm HTTP/1.1" 200 365 0.001001
127.0.0.1 - - [2018-10-02 18:32:15] "POST /socket.io/?EIO=3&transport=polling&t=MOrdtRR&sid=b654279ca4a449f4a610ffb10ebd45bd HTTP/1.1" 200 195 0.000998
127.0.0.1 - - [2018-10-02 18:32:15] "GET /socket.io/?EIO=3&transport=polling&t=MOrdnKo&sid=b654279ca4a449f4a610ffb10ebd45bd HTTP/1.1" 200 211 25.311718
message handler error
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\engineio\server.py", line 411, in _trigger_event
    return self.handlers[event](*args)
  File "C:\Anaconda3\lib\site-packages\socketio\server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "C:\Anaconda3\lib\site-packages\socketio\server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "C:\Anaconda3\lib\site-packages\socketio\server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Anaconda3\lib\site-packages\socketio\server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "c:\users\albel\documents\rasanlutrainer\rasa install\core\rasa_core\channels\socketio.py", line 142, in handle_message
    message = UserMessage(data['message'], output_channel, sid,
KeyError: 'message'
```
my python code is :

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os
import logging
import warnings
import ruamel

from rasa_core.channels.socketio import SocketIOInput
from rasa_core.agent import Agent
from rasa_core.interpreter import RegexInterpreter
from rasa_core.interpreter import RasaNLUInterpreter

logger = logging.getLogger(__name__)



def run_bot():
    interpreter = RasaNLUInterpreter('./models/nlu/default/demobotnlu')
    #agent = Agent.load('./models/dialogue/', interpreter=RegexInterpreter())
    agent = Agent.load('./models/dialogue/', interpreter=interpreter)
    input_channel = SocketIOInput(
            # event name for messages sent from the user
            user_message_evt="user_uttered",
            # event name for messages sent from the bot
            bot_message_evt="bot_uttered",
            # socket.io namespace to use for the messages
            namespace=None)
    # set serve_forever=False if you want to keep the server running
    s = agent.handle_channels([input_channel], 5600, serve_forever=True)


if __name__ == '__main__':
	warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)
	run_bot()

```

What is triggering this message ?

Thanks for your feedbak

**Comment by znat** [comment]
Hi, are you using the latest version of the widget?

**Comment by arcontechnologies** [comment]
Hi, I guess so : rasa_addons-0.4.3

**Comment by znat** [comment]
I meant the latest rasa-webchat. You might have a cached version in your browser

**Comment by znat** [comment]
This should be fixed if you use the latest version of the widget (not the addons)
