### ISSUE TITLE
h"File not found!".format(os.path.abspath(filename)))

### ISSUE THREAD

**Issue by mukund-pst** [mrbot-ai/rasa-webchat#76]
$ python3 -m rasa_core.run -d models/dialogue

2019-04-19 14:15:54 INFO     root  - Rasa process starting
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/posit/.local/lib/python3.6/site-packages/rasa_core/run.py", line 251, in <module>
    endpoints=_endpoints)
  File "/home/posit/.local/lib/python3.6/site-packages/rasa_core/run.py", line 221, in load_agent
    action_endpoint=endpoints.action)
  File "/home/posit/.local/lib/python3.6/site-packages/rasa_core/agent.py", line 261, in load
    domain = Domain.load(os.path.join(path, "domain.yml"))
  File "/home/posit/.local/lib/python3.6/site-packages/rasa_core/domain.py", line 87, in load
    "File not found!".format(os.path.abspath(filename)))
Exception: Failed to load domain specification from '/home/posit/.local/lib/python3.6/site-packages/rasa_core/models/dialogue/domain.yml'. File not found!

**Comment by znat** [comment]
Not a webchat problem, but a Rasa one.
