### ISSUE TITLE
Unable to install rasa-webchat

### ISSUE THREAD

**Issue by azizullah2017** [mrbot-ai/rasa-webchat#8]
Node version : v6.11.5
React version : 16.5.2
npm version : 3.5.2
yarn version : 1.10.1

npm:
sudo npm install --save react-chat-widget
yarn
sudo yarn add react-chat-widget

can anyone tell. what is the dependencies ?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v6.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rasa-webchat@0.3.3~prebuild: rasa-webchat@0.3.3
6 silly lifecycle rasa-webchat@0.3.3~prebuild: no script for prebuild, continuing
7 info lifecycle rasa-webchat@0.3.3~build: rasa-webchat@0.3.3
8 verbose lifecycle rasa-webchat@0.3.3~build: unsafe-perm in lifecycle true
9 verbose lifecycle rasa-webchat@0.3.3~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/user/Videos/rasa-webchat-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/java/jdk-10/bin:/usr/local/java/jdk-10/jre/bin
10 verbose lifecycle rasa-webchat@0.3.3~build: CWD: /home/user/Videos/rasa-webchat-master
11 silly lifecycle rasa-webchat@0.3.3~build: Args: [ '-c', 'webpack-cli --config webpack.prod.js' ]
12 silly lifecycle rasa-webchat@0.3.3~build: Returned: code: 2  signal: null
13 info lifecycle rasa-webchat@0.3.3~build: Failed to exec build script
14 verbose stack Error: rasa-webchat@0.3.3 build: `webpack-cli --config webpack.prod.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid rasa-webchat@0.3.3
16 verbose cwd /home/user/Videos/rasa-webchat-master
17 error Linux 4.13.0-46-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v6.11.4
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error rasa-webchat@0.3.3 build: `webpack-cli --config webpack.prod.js`
22 error Exit status 2
23 error Failed at the rasa-webchat@0.3.3 build script 'webpack-cli --config webpack.prod.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the rasa-webchat package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-cli --config webpack.prod.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs rasa-webchat
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls rasa-webchat
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by znat** [comment]
@azizullah2017
We're working on it. At this time, `rasa-webchat` is not npm installable (the command you ran installs the project it is forked from), but it is going to be in a few days.
In the meantime, you can only use it as a JS snippet in a `<script>` tag (see readme)

**Comment by TheoTomalty** [comment]
You should be able to install rasa-webchat now, the command is
``` bash
npm install mrbot-ai/rasa-webchat
```
Note that it will appear to be hanging but it just takes a really long time to install.

**Comment by TheoTomalty** [comment]
@azizullah2017 it looks like this is because you are using an old version of node, and it is interacting badly with one of the dependencies. It will likely work if you update and try again. The same issue here https://github.com/sequelize/cli/issues/291

**Comment by azizullah2017** [comment]
@TheoTomalty I am still facing the error.
**node version : v10.12.0**
**npm version: 6.4.1**

```
sudo npm install mrbot-ai/rasa-webchat
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > husky@0.13.4 install /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/husky
npm ERR! prepareGitDep > node ./bin/install.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep husky
npm ERR! prepareGitDep setting up hooks
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > node-sass@4.8.3 install /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/install.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > node-sass@4.8.3 postinstall /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/build.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Building: /usr/local/bin/node /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep { Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/.git/hooks'
npm ERR! prepareGitDep     at Object.mkdirSync (fs.js:750:3)
npm ERR! prepareGitDep     at createHook (/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/husky/src/index.js:175:36)
npm ERR! prepareGitDep     at /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/husky/src/index.js:221:21
npm ERR! prepareGitDep     at Array.map (<anonymous>)
npm ERR! prepareGitDep     at Object.installFrom (/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/husky/src/index.js:217:10)
npm ERR! prepareGitDep     at Object.<anonymous> (/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/husky/bin/install.js:17:7)
npm ERR! prepareGitDep     at Module._compile (internal/modules/cjs/loader.js:688:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:598:32)
npm ERR! prepareGitDep     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
npm ERR! prepareGitDep   errno: -13,
npm ERR! prepareGitDep   syscall: 'mkdir',
npm ERR! prepareGitDep   code: 'EACCES',
npm ERR! prepareGitDep   path: '/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/.git/hooks' }
npm ERR! prepareGitDep Unable to save binary /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass/vendor'
npm ERR! prepareGitDep     at Object.mkdirSync (fs.js:750:3)
npm ERR! prepareGitDep     at sync (/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/mkdirp/index.js:71:13)
npm ERR! prepareGitDep     at Function.sync (/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/mkdirp/index.js:77:24)
npm ERR! prepareGitDep     at checkAndDownloadBinary (/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass/scripts/install.js:114:11)
npm ERR! prepareGitDep     at Object.<anonymous> (/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass/scripts/install.js:157:1)
npm ERR! prepareGitDep     at Module._compile (internal/modules/cjs/loader.js:688:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:598:32)
npm ERR! prepareGitDep     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! prepareGitDep   errno: -13,
npm ERR! prepareGitDep   syscall: 'mkdir',
npm ERR! prepareGitDep   code: 'EACCES',
npm ERR! prepareGitDep   path:
npm ERR! prepareGitDep    '/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass/vendor' }
npm ERR! prepareGitDep gyp info it worked if it ends with ok
npm ERR! prepareGitDep gyp verb cli [ '/usr/local/bin/node',
npm ERR! prepareGitDep gyp verb cli   '/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! prepareGitDep gyp verb cli   'rebuild',
npm ERR! prepareGitDep gyp verb cli   '--verbose',
npm ERR! prepareGitDep gyp verb cli   '--libsass_ext=',
npm ERR! prepareGitDep gyp verb cli   '--libsass_cflags=',
npm ERR! prepareGitDep gyp verb cli   '--libsass_ldflags=',
npm ERR! prepareGitDep gyp verb cli   '--libsass_library=' ]
npm ERR! prepareGitDep gyp info using node-gyp@3.6.2
npm ERR! prepareGitDep gyp info using node@10.12.0 | linux | x64
npm ERR! prepareGitDep gyp verb command rebuild []
npm ERR! prepareGitDep gyp verb command clean []
npm ERR! prepareGitDep gyp verb clean removing "build" directory
npm ERR! prepareGitDep gyp verb command configure []
npm ERR! prepareGitDep gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! prepareGitDep gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! prepareGitDep gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
npm ERR! prepareGitDep gyp verb get node dir no --target version specified, falling back to host node version: 10.12.0
npm ERR! prepareGitDep gyp verb command install [ '10.12.0' ]
npm ERR! prepareGitDep gyp verb install input version string "10.12.0"
npm ERR! prepareGitDep gyp verb install installing version: 10.12.0
npm ERR! prepareGitDep gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! prepareGitDep gyp verb install version is already installed, need to check "installVersion"
npm ERR! prepareGitDep gyp verb got "installVersion" 9
npm ERR! prepareGitDep gyp verb needs "installVersion" 9
npm ERR! prepareGitDep gyp verb install version is good
npm ERR! prepareGitDep gyp verb get node dir target node version installed: 10.12.0
npm ERR! prepareGitDep gyp verb build dir attempting to create "build" dir: /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass/build
npm ERR! prepareGitDep gyp ERR! configure error 
npm ERR! prepareGitDep gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass/build'
npm ERR! prepareGitDep gyp ERR! System Linux 4.13.0-46-generic
npm ERR! prepareGitDep gyp ERR! command "/usr/local/bin/node" "/home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! prepareGitDep gyp ERR! cwd /home/user/.npm/_cacache/tmp/git-clone-97fa0a42/node_modules/node-sass
npm ERR! prepareGitDep gyp ERR! node -v v10.12.0
npm ERR! prepareGitDep gyp ERR! node-gyp -v v3.6.2
npm ERR! prepareGitDep gyp ERR! not ok 
npm ERR! prepareGitDep Build failed with error code: 1
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! node-sass@4.8.3 postinstall: `node scripts/build.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the node-sass@4.8.3 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/user/.npm/_logs/2018-10-19T05_05_40_736Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-10-19T05_05_41_979Z-debug.log

```

**Comment by TheoTomalty** [comment]
@azizullah2017 This looks like a permissions problem similar to https://github.com/npm/npm/issues/7407.

**Comment by azizullah2017** [comment]
@TheoTomalty 
``` $ sudo npm install mrbot-ai/rasa-webchat
[sudo] password for user: 
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > node-sass@4.9.4 install /home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/install.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > node-sass@4.9.4 postinstall /home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/build.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Building: /usr/local/bin/node /home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep Unable to save binary /home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass/vendor'
npm ERR! prepareGitDep     at Object.mkdirSync (fs.js:750:3)
npm ERR! prepareGitDep     at sync (/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/mkdirp/index.js:71:13)
npm ERR! prepareGitDep     at Function.sync (/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/mkdirp/index.js:77:24)
npm ERR! prepareGitDep     at checkAndDownloadBinary (/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass/scripts/install.js:114:11)
npm ERR! prepareGitDep     at Object.<anonymous> (/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass/scripts/install.js:157:1)
npm ERR! prepareGitDep     at Module._compile (internal/modules/cjs/loader.js:688:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:598:32)
npm ERR! prepareGitDep     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! prepareGitDep   errno: -13,
npm ERR! prepareGitDep   syscall: 'mkdir',
npm ERR! prepareGitDep   code: 'EACCES',
npm ERR! prepareGitDep   path:
npm ERR! prepareGitDep    '/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass/vendor' }
npm ERR! prepareGitDep gyp info it worked if it ends with ok
npm ERR! prepareGitDep gyp verb cli [ '/usr/local/bin/node',
npm ERR! prepareGitDep gyp verb cli   '/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! prepareGitDep gyp verb cli   'rebuild',
npm ERR! prepareGitDep gyp verb cli   '--verbose',
npm ERR! prepareGitDep gyp verb cli   '--libsass_ext=',
npm ERR! prepareGitDep gyp verb cli   '--libsass_cflags=',
npm ERR! prepareGitDep gyp verb cli   '--libsass_ldflags=',
npm ERR! prepareGitDep gyp verb cli   '--libsass_library=' ]
npm ERR! prepareGitDep gyp info using node-gyp@3.8.0
npm ERR! prepareGitDep gyp info using node@10.12.0 | linux | x64
npm ERR! prepareGitDep gyp verb command rebuild []
npm ERR! prepareGitDep gyp verb command clean []
npm ERR! prepareGitDep gyp verb clean removing "build" directory
npm ERR! prepareGitDep gyp verb command configure []
npm ERR! prepareGitDep gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! prepareGitDep gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! prepareGitDep gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.14
npm ERR! prepareGitDep gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! prepareGitDep gyp verb get node dir no --target version specified, falling back to host node version: 10.12.0
npm ERR! prepareGitDep gyp verb command install [ '10.12.0' ]
npm ERR! prepareGitDep gyp verb install input version string "10.12.0"
npm ERR! prepareGitDep gyp verb install installing version: 10.12.0
npm ERR! prepareGitDep gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! prepareGitDep gyp verb install version is already installed, need to check "installVersion"
npm ERR! prepareGitDep gyp verb got "installVersion" 9
npm ERR! prepareGitDep gyp verb needs "installVersion" 9
npm ERR! prepareGitDep gyp verb install version is good
npm ERR! prepareGitDep gyp verb get node dir target node version installed: 10.12.0
npm ERR! prepareGitDep gyp verb build dir attempting to create "build" dir: /home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass/build
npm ERR! prepareGitDep gyp ERR! configure error 
npm ERR! prepareGitDep gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass/build'
npm ERR! prepareGitDep gyp ERR! System Linux 4.13.0-46-generic
npm ERR! prepareGitDep gyp ERR! command "/usr/local/bin/node" "/home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! prepareGitDep gyp ERR! cwd /home/user/.npm/_cacache/tmp/git-clone-e2642740/node_modules/node-sass
npm ERR! prepareGitDep gyp ERR! node -v v10.12.0
npm ERR! prepareGitDep gyp ERR! node-gyp -v v3.8.0
npm ERR! prepareGitDep gyp ERR! not ok 
npm ERR! prepareGitDep Build failed with error code: 1
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/user/.npm/_logs/2018-10-22T05_16_52_116Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-10-22T05_16_52_306Z-debug.log
```

**Comment by TheoTomalty** [comment]
Hi @azizullah2017, the permissions error is still coming from your .npm directory. This is a common issue with npm, with the solution [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

It looks like even though you are installing locally, the git repo is being cloned to the tmp directory in your global .npm directory (/home/user/.npm/_cacache/tmp) which has restricted permissions. If you follow the steps in the link it should fix the issue. I hope this helps.

**Comment by mba1995** [comment]
`npm ERR! path project_path\node_modules\.bin\jsesc.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete  project_path\node_modules\.bin\jsesc.cmd: ..\@babel\core\node_modules\jsesc\bin\jsesc symlink target is not controlled by npm  project_path\node_modules\jsesc
npm ERR! File exists:  project_path\node_modules\.bin\jsesc.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-03-25T10_51_47_513Z-debug.log
`
When I try to install rasa-webchat package into my app, It returns this issue. Not sure what's related to and how to solve this. 
Any help would be appreciated.
